[project]
name = "soma"
version = "0.1.0"
requires-python = ">=3.10"

[tool.poetry.dependencies]
numpy = "^2.2.3"
pandas = "^2.2.3"
scipy = "^1.15.2"
scikit-image = "^0.25.2"
opencv-python = "^4.11.0.86"
